name = "ns"
compatibility_date = "2024-06-01"
main = "src/index.ts"

[build]
command = "npm run build"

[triggers]
crons = []

[vars]
NS_GCP_API_URL = ""
NS_GCP_SHARED_SECRET = ""

[env.dev]
# 仅开发环境可选配置
